### ISSUE TITLE
Can't build mpd - Dependency "boost" not found

### ISSUE THREAD

**Issue by duhow** [patrickkfkan/volumio-build-mpd#1]
I'm using Docker image `debian:8e9f8546050d` , when finally all the dependencies were installed, `mpd` couldn't continue with build due to `boost` package not found.

```
root@d5cdbc9c6555:/volumio-build-mpd# ./build.sh --target=armv7 --prefix=/opt/mympd --output=mympd.tar.gz -j8
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Target arch       :  armv7
Prefix            :  /opt/mympd
Binary package    :  /volumio-build-mpd/targets/mympd.tar.gz
Include mpc       :  yes
Make concurrency  :  8

Note: Prefix will be the path to the MPD build on your target device 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Continue [y/n]? y
Entering build for package 'toolchain' 
Entering directory /volumio-build-mpd/src/toolchain...
Entering directory /volumio-build-mpd/build/armv7/toolchain...
Generated: /volumio-build-mpd/build/armv7/toolchain/config/cmake-toolchain.txt
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOOLCHAIN_DIR="/volumio-build-mpd/build/armv7/toolchain"
BUILD_TARGET="arm-linux-gnueabihf"
BUILD_CC="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-gcc"
BUILD_CXX="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-g++"
BUILD_AR="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-ar"
BUILD_RANLIB="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-ranlib"
BUILD_OBJCOPY="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-objcopy"
BUILD_STRIP="/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-strip"
BUILD_CFLAGS="-I/volumio-build-mpd/staging/armv7//opt/mympd/include"
BUILD_LDFLAGS="-L/volumio-build-mpd/staging/armv7//opt/mympd/lib -Wl,--rpath-link=/volumio-build-mpd/staging/armv7//opt/mympd/lib -Wl,--rpath-link=/volumio-build-mpd/staging/armv7//opt/mympd/lib/pulseaudio -Wl,--rpath-link=/volumio-build-mpd/staging/armv7//opt/mympd/lib/private -Wl,--rpath=/opt/mympd/arm-linux-gnueabihf/lib -Wl,--rpath=/opt/mympd/lib -Wl,--dynamic-linker=/opt/mympd/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3"
BUILD_PKG_CONFIG_LIBDIR="/volumio-build-mpd/staging/armv7//opt/mympd/lib/pkgconfig"
BUILD_PKG_CONFIG_SYSROOT_DIR="/volumio-build-mpd/staging/armv7"
PATH="/volumio-build-mpd/build/armv7/toolchain/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
TOOLCHAIN_CMAKE="/volumio-build-mpd/build/armv7/toolchain/config/cmake-toolchain.txt"
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Leaving build for package 'toolchain' 
Entering build for package 'mpd' 
Entering directory /volumio-build-mpd/src/mpd...
Using cached download
Unpacking /volumio-build-mpd/src/mpd/mpd-0.22.2.tar.xz...
Entering directory /volumio-build-mpd/build/armv7/mpd-build...
Entering preconfigure_package... 
Entering configure_package... 
Generated: ./cross-file.build
DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: c_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
DEPRECATION: cpp_link_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
The Meson build system
Version: 0.56.0
Source dir: /volumio-build-mpd/build/armv7/mpd
Build dir: /volumio-build-mpd/build/armv7/mpd-build/output/release
Build type: cross build
WARNING: Unknown options: "build.c_std, build.cpp_std"
The value of new options can be set with:
meson setup <builddir> --reconfigure -Dnew_option=new_value ...
Project name: mpd
Project version: 0.22.2
C compiler for the host machine: /volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-gcc (gcc 8.3.0 "arm-linux-gnueabihf-gcc (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 8.3.0")
C linker for the host machine: /volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-gcc ld.bfd 8.3-2019
C++ compiler for the host machine: /volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-g++ (gcc 8.3.0 "arm-linux-gnueabihf-g++ (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 8.3.0")
C++ linker for the host machine: /volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-g++ ld.bfd 8.3-2019
C compiler for the build machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
C linker for the build machine: cc ld.bfd 2.31.1
C++ compiler for the build machine: c++ (gcc 8.3.0 "c++ (Debian 8.3.0-6) 8.3.0")
C++ linker for the build machine: c++ ld.bfd 2.31.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: arm
Target machine cpu: any
Found git repository at /volumio-build-mpd
Configuring Version.h using configuration
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -Wdouble-promotion: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Compiler for C++ supports arguments -ftree-vectorize: YES 
Compiler for C++ supports arguments -fno-threadsafe-statics: YES 
Compiler for C++ supports arguments -fmerge-all-constants: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Wsign-compare: YES 
Compiler for C++ supports arguments -Wcomma: NO 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wheader-hygiene: NO 
Compiler for C++ supports arguments -Winconsistent-missing-destructor-override: NO 
Compiler for C++ supports arguments -Wunreachable-code-break: NO 
Compiler for C++ supports arguments -Wunused: YES 
Compiler for C++ supports arguments -Wused-but-marked-unused: NO 
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES 
Compiler for C++ supports arguments -ffunction-sections: YES 
Compiler for C++ supports arguments -fdata-sections: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -Wdouble-promotion: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -ffast-math: YES 
Compiler for C supports arguments -ftree-vectorize: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -pedantic: YES 
Compiler for C supports arguments -ffunction-sections: YES 
Compiler for C supports arguments -fdata-sections: YES 
Compiler for C++ supports link arguments -Wl,--gc-sections: YES 
Checking for function "getpwnam_r" : YES 
Checking for function "getpwuid_r" : YES 
Checking for function "initgroups" : YES 
Checking for function "fnmatch" : YES 
Checking for function "strndup" : YES 
Checking for function "strcasestr" : YES 
Checking for function "syslog" : YES 
Found pkg-config: /usr/bin/pkg-config (0.29)
Run-time dependency Boost found: NO 

../mpd/meson.build:206:0: ERROR: Dependency "boost" not found

A full log can be found at /volumio-build-mpd/build/armv7/mpd-build/output/release/meson-logs/meson-log.txt
configure_package returned error
```

Additional info:

```
Checking for function "syslog" : YES 
None of 'BOOST_INCLUDEDIR' are defined in the environment, not changing global flags.
None of 'BOOST_LIBRARYDIR' are defined in the environment, not changing global flags.
None of 'BOOST_ROOT' are defined in the environment, not changing global flags.
None of 'BOOSTROOT' are defined in the environment, not changing global flags.
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary for 1 specified from cross file, native file, or env var as ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29)
Determining dependency 'boost' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion boost` -> 1

Checking potential boost root /volumio-build-mpd/build/armv7/toolchain/arm-linux-gnueabihf/include/c++
Checking potential boost root /volumio-build-mpd/build/armv7/toolchain/arm-linux-gnueabihf/include/c++/8.3.0
Checking potential boost root /volumio-build-mpd/build/armv7/toolchain/lib/gcc/arm-linux-gnueabihf/8.3.0
Checking potential boost root /volumio-build-mpd/build/armv7/toolchain/arm-linux-gnueabihf
Checking potential boost root /volumio-build-mpd/build/armv7/toolchain/arm-linux-gnueabihf/libc/usr
Checking potential boost root /usr/local
Checking potential boost root /usr
Run-time dependency Boost found: NO 

../mpd/meson.build:206:0: ERROR: Dependency "boost" not found
```

**Comment by duhow** [comment]
By adding the `BOOST_ROOT` environment variable it works:

```
BOOST_ROOT=/volumio-build-mpd/build/armv7/boost
```

**Comment by mac167** [comment]
me too, can't install on pi4, it says lack of space.  You have a better solution to install it.  thank you!

**Comment by patrickkfkan** [comment]
Hi @duhow,

Thanks for pointing this out. I actually did my build in a Debian Buster chroot cage and didn't have to set this environment variable. I haven't checked why, but since Volumio Buster is likely to be released soon this kind of build may no longer be necessary (we'll see...). But thanks anyway, and I'll put this in if I ever need to update the package (or you may submit a PR if you want :smile: )

@mac167 , pi4 running out of space has nothing to do with this issue or the build itself, no?

**Comment by mac167** [comment]
Hi patrickkfkan !
this all my setup:, thank for advice and you can make the sample: mpd-0.21.16.arm-20191228-3v3jy.tar
for easy setup?? thank you very much!

          © 2015-2020 Michelangelo Guarise - Volumio Team - Volumio.org

Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Welcome to Volumio for Raspberry Pi (5.4.79-v7l+ armv7l)
Last login: Mon Jan 11 10:04:50 2021 from 192.168.88.105
volumio@volumio:~$ apt install build-essential wget rsync gawk bison \
> python python3 python3-pip cmake autoconf libtool \
> git pkg-config gettext intltool qemu-user-static \
> libgcrypt20-dev gperf libglib2.0-dev docbook-xsl \
> xsltproc libncurses-dev flex texinfo
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission d                                                                                                             enied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are y                                                                                                             ou root?
volumio@volumio:~$ ^C
volumio@volumio:~$ Volumio Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, t                                                                                                             o the extent
-bash: Volumio: command not found
volumio@volumio:~$ permitted by applicable law.
-bash: permitted: command not found
volumio@volumio:~$ Welcome to Volumio for Raspberry Pi (5.4.79-v7l+ armv7l)
-bash: syntax error near unexpected token `('
volumio@volumio:~$ Last login: Mon Jan 11 10:04:50 2021 from 192.168.88.105
-bash: Last: command not found
volumio@volumio:~$ volumio@volumio:~$ apt install build-essential wget rsync gaw                                                                                                             k bison \
> > python python3 python3-pip cmake autoconf libtool \
> > git pkg-config gettext intltool qemu-user-static \
> > libgcrypt20-dev gperf libglib2.0-dev docbook-xsl \
> > xsltproc libncurses-dev flex texinfo
-bash: volumio@volumio:~$: command not found
volumio@volumio:~$ E: Could not open lock file /var/lib/dpkg/lock-frontend - ope                                                                                                             n (13: Permission d                                                                                                                                                                                                                          enied)
-bash: syntax error near unexpected token `('
volumio@volumio:~$ E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lo                                                                                                             ck-frontend), are y                                                                                                                                                                                                                          ou root?
-bash: syntax error near unexpected token `('
volumio@volumio:~$ volumio@volumio:~$
-bash: volumio@volumio:~$: command not found
volumio@volumio:~$
volumio@volumio:~$ y
-bash: y: command not found
volumio@volumio:~$  sudo apt install yasm
[sudo] password for volumio:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  yasm
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 289 kB of archives.
After this operation, 1407 kB of additional disk space will be used.
Get:1 https://mirror.freedif.org/Raspbian/raspbian buster/main armhf yasm armhf                                                                                                              1.3.0-2 [289 kB]
Fetched 289 kB in 3s (112 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package yasm.
(Reading database ... 51289 files and directories currently installed.)
Preparing to unpack .../yasm_1.3.0-2_armhf.deb ...
Unpacking yasm (1.3.0-2) ...
Setting up yasm (1.3.0-2) ...
Processing triggers for man-db (2.8.5-2) ...
volumio@volumio:~$  cd ~
volumio@volumio:~$ git clone https://github.com/patrickkfkan/volumio-build-mpd.g                                                                                                             it
Cloning into 'volumio-build-mpd'...
remote: Enumerating objects: 354, done.
remote: Counting objects: 100% (354/354), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 354 (delta 131), reused 345 (delta 122), pack-reused 0
Receiving objects: 100% (354/354), 5.78 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (131/131), done.
volumio@volumio:~$ cd volumio-build-mpd
volumio@volumio:~/volumio-build-mpd$ ./build.sh --target=armv7 --prefix=/opt/mym                                                                                                             pd --output=mympd.tar.gz -j8
--------------------------------------------------------------------------------
Target arch       :  armv7
Prefix            :  /opt/mympd
Binary package    :  /home/volumio/volumio-build-mpd/targets/mympd.tar.gz
Include mpc       :  yes
Make concurrency  :  8

Note: Prefix will be the path to the MPD build on your target device
--------------------------------------------------------------------------------
Continue [y/n]? y
Entering build for package 'toolchain'
Entering directory /home/volumio/volumio-build-mpd/src/toolchain...
Downloading package source...
--2021-01-11 10:10:30--  https://developer.arm.com/-/media/Files/downloads/gnu-a                                                                                                             /8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
Resolving developer.arm.com (developer.arm.com)... 23.76.211.201
Connecting to developer.arm.com (developer.arm.com)|23.76.211.201|:443... connec                                                                                                             ted.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/                                                                                                             8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz [follow                                                                                                             ing]
--2021-01-11 10:10:33--  https://armkeil.blob.core.windows.net/developer/Files/d                                                                                                             ownloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf                                                                                                             .tar.xz
Resolving armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)... 52.23                                                                                                             9.137.100
Connecting to armkeil.blob.core.windows.net (armkeil.blob.core.windows.net)|52.2                                                                                                             39.137.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 256094408 (244M) [application/octet-stream]
Saving to: 'gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz'

.tar.xz                                           1%[>                                                                                                                                                                                                                 ]   4.                                                                                                             .tar.xz                                         100%[====================================================================================================>] 244.23M   493KB/s    in 9m 43s

2021-01-11 10:20:17 (429 KB/s) - 'gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz' saved [256094408/256094408]

Unpacking /home/volumio/volumio-build-mpd/src/toolchain/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz...
Entering directory /home/volumio/volumio-build-mpd/build/armv7/toolchain...
Entering directory /home/volumio/volumio-build-mpd/build/armv7/toolchain...
Generated: /home/volumio/volumio-build-mpd/build/armv7/toolchain/config/cmake-toolchain.txt
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOOLCHAIN_DIR="/home/volumio/volumio-build-mpd/build/armv7/toolchain"
BUILD_TARGET="arm-linux-gnueabihf"
BUILD_CC="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-gcc"
BUILD_CXX="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-g++"
BUILD_AR="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-ar"
BUILD_RANLIB="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-ranlib"
BUILD_OBJCOPY="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-objcopy"
BUILD_STRIP="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin/arm-linux-gnueabihf-strip"
BUILD_CFLAGS="-I/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/include"
BUILD_LDFLAGS="-L/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/lib -Wl,--rpath-link=/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/lib -Wl,--rpath-link=/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/lib/pulseaudio -Wl,--rpath-link=/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/lib/private -Wl,--rpath=/opt/mympd/arm-linux-gnueabihf/lib -Wl,--rpath=/opt/mympd/lib -Wl,--dynamic-linker=/opt/mympd/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3"
BUILD_PKG_CONFIG_LIBDIR="/home/volumio/volumio-build-mpd/staging/armv7//opt/mympd/lib/pkgconfig"
BUILD_PKG_CONFIG_SYSROOT_DIR="/home/volumio/volumio-build-mpd/staging/armv7"
PATH="/home/volumio/volumio-build-mpd/build/armv7/toolchain/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
TOOLCHAIN_CMAKE="/home/volumio/volumio-build-mpd/build/armv7/toolchain/config/cmake-toolchain.txt"
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Leaving build for package 'toolchain'
Entering build for package 'kernel-headers'
Entering directory /home/volumio/volumio-build-mpd/src/kernel-headers...
Downloading package source...
--2021-01-11 10:21:20--  https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.1.tar.xz
Resolving cdn.kernel.org (cdn.kernel.org)... 151.101.129.176, 151.101.193.176, 151.101.1.176, ...
Connecting to cdn.kernel.org (cdn.kernel.org)|151.101.129.176|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 109435656 (104M) [application/x-xz]
Saving to: 'linux-5.4.1.tar.xz'

                                                100%[====================================================================================================>] 104.37M  7.30MB/s    in 16s

2021-01-11 10:21:42 (6.63 MB/s) - 'linux-5.4.1.tar.xz' saved [109435656/109435656]

Unpacking /home/volumio/volumio-build-mpd/src/kernel-headers/linux-5.4.1.tar.xz...
tar: arch/arm64/boot/dts/arm: Directory renamed before its status could be extracted
tar: arch/arm64/boot/dts: Directory renamed before its status could be extracted
tar: arch/arm64/boot: Directory renamed before its status could be extracted
tar: arch/arm64: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
Build for package 'kernel-headers' not completed
volumio@volumio:~/volumio-build-mpd$

**Comment by duhow** [comment]
@mac167 as @patrickkfkan said, your issue is not related to mine, it's completely different.
Also you should **build** this package OUTSIDE of Volumio. In another Linux machine, or with Docker.
I'm closing this one.
